version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - JWT_SECRET=your_jwt_secret
      - RATE_LIMIT=60
      - SENTRY_DSN=your_sentry_dsn
    depends_on:
      - db
      - redis

  db:
    image: sqlite

  redis:
    image: redis
    ports:
      - '6379:6379'
